// @ts-check

/**
 * Sidebar configuration for ClusterChirp Docs.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro', // if you have docs/intro.md or change path accordingly
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;

