// @ts-check

/**
 * Sidebar configuration for ClusterChirp Docs.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'FAQ',
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
  ],
};

export default sidebars;

